#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

## Global yabai settings
yabai -m config external_bar                 main:40:0      
yabai -m config menubar_opacity              1.0            
yabai -m config mouse_follows_focus          off            
yabai -m config focus_follows_mouse          off            
yabai -m config display_arrangement_order    default        
yabai -m config window_origin_display        default        
yabai -m config window_placement             second_child   
yabai -m config window_insertion_point       focused        
yabai -m config window_zoom_persist          on             
yabai -m config window_shadow                on             
yabai -m config window_animation_duration    0.0            
yabai -m config window_animation_easing      ease_out_circ  
yabai -m config window_opacity_duration      0.0            
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0            
yabai -m config normal_window_opacity        0.95           
yabai -m config insert_feedback_color        0xffd75f5f     
yabai -m config split_ratio                  0.50           
yabai -m config split_type                   auto           
yabai -m config auto_balance                 off            
yabai -m config top_padding                  8              
yabai -m config bottom_padding               8              
yabai -m config left_padding                 8              
yabai -m config right_padding                8              
yabai -m config window_gap                   8              
yabai -m config layout                       bsp            
yabai -m config mouse_modifier               fn             
yabai -m config mouse_action1                move           
yabai -m config mouse_action2                resize         
yabai -m config mouse_drop_action            swap

~/.config/yabai/setup_spaces.sh

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

# vim: set ft=sh :
