background = 0xCC000000
base = 0x26000000
alternate_base = 0x33000000
text = 0xFFFFFFFF
bright_text = 0xFFA7A7A7
accent = 0xFFFFFFFF
accent_secondary = 0xFFBFBFBF

font_size = 13
small_font_size = 12
h1_size = 22
h2_size = 16
h3_size = 14

font_family = VictorMono NFM
font_family_monospace = VictorMono NFM
icon_theme = Adwaita

rounding_large = 0
rounding_small = 0
