$mod = SUPER

env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Adwaita
env = HYPRCURSOR_SIZE,24

monitor = HDMI-A-1,2560x1440@119.998,auto,1

general {
    gaps_in = 8
    gaps_out = 0
    border_size = 1
    layout = dwindle
}

decoration {
    rounding = 0

    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

input {
    kb_layout = us
    kb_variant = intl
    repeat_delay = 150
    repeat_rate = 80

    touchpad {
        natural_scroll = false
    }
}

device {
    name = dream117er-explorer-keyboard-blank-mouse
    accel_profile = adaptive
    sensitivity = -0.5
}

device {
    name = logitech-ergo-m575
    accel_profile = adaptive
    sensitivity = 0.3
}

exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland XDG_SESSION_DESKTOP=Hyprland DESKTOP_SESSION=Hyprland
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP DESKTOP_SESSION
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper
exec-once = hypridle
exec-once = quickshell -p $HOME/.config/quickshell

workspace = name:B, persistent:true
workspace = name:T, persistent:true
workspace = name:M, persistent:true
workspace = name:W, persistent:true
workspace = name:X, persistent:true

windowrule = match:title ^(Picture-in-picture)$, float on, pin on, size 512 288, move 2032 1136, suppress_event activate activate_focus
windowrule = match:title ^(Bitwarden)$, float on

windowrule = match:class ^(kitty)$, workspace name:T
windowrule = match:title ^(Chromium - Bruno)$, workspace name:B
windowrule = match:title ^(Chromium - Squibler)$, workspace name:W
windowrule = match:title ^(YouTube Music)$, workspace name:M

windowrule = match:class negative:^(kitty|hyprpwcenter)$, no_blur on
layerrule = match:namespace (quickshell|quickshell-.*)$, blur on

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl= , XF86AudioPlay, exec, playerctl play-pause

bind = ALT, h, movefocus, l
bind = ALT, j, movefocus, d
bind = ALT, k, movefocus, u
bind = ALT, l, movefocus, r

bind = ALT SHIFT, h, movewindow, l
bind = ALT SHIFT, j, movewindow, d
bind = ALT SHIFT, k, movewindow, u
bind = ALT SHIFT, l, movewindow, r

bind = ALT, b, workspace, name:B
bind = ALT, t, workspace, name:T
bind = ALT, m, workspace, name:M
bind = ALT, w, workspace, name:W
bind = ALT, x, workspace, name:X

bind = ALT SHIFT, b, movetoworkspace, name:B
bind = ALT SHIFT, t, movetoworkspace, name:T
bind = ALT SHIFT, m, movetoworkspace, name:M
bind = ALT SHIFT, w, movetoworkspace, name:W
bind = ALT SHIFT, x, movetoworkspace, name:X

bind = SUPER, q, killactive
bind = SUPER, Return, exec, kitty

bind = SUPER, p, exec, quickshell ipc -p $HOME/.config/quickshell call -- dashboard toggle
bind = SUPER, space, exec, quickshell ipc -p $HOME/.config/quickshell call -- launcher show
bind = SUPER, v, exec,  quickshell ipc -p $HOME/.config/quickshell call -- clipboard toggle
bind = SUPER, s, exec, quickshell ipc -p $HOME/.config/quickshell call -- screenshot toggle
bind = SUPER, n, exec, quickshell ipc -p $HOME/.config/quickshell call -- notifications toggle
bind = SUPER SHIFT, q, exec, quickshell ipc -p $HOME/.config/quickshell call -- session toggle

bind = SUPER SHIFT, l, exec, hyprlock

bind = ALT, semicolon, submap, service

submap = service

bind = , escape, submap, reset
bind = , r, exec, hyprctl reload

bind = , f, togglefloating
bind = , u, pin

bind = , h, resizeactive, -50 0
bind = , l, resizeactive, 50 0

submap = reset
