background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 7
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(255,255,255,0.93)
    font_family = VictorMono NFM
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%a %d %b')"
    color = rgba(255,255,255,0.82)
    font_family = VictorMono NFM
    font_size = 22
    position = 0, 25
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255,255,255,0.80)
    inner_color = rgba(0,0,0,0.85)
    font_color = rgba(255,255,255,0.95)
    fade_on_empty = false
    placeholder_text =
    position = 0, -90
    halign = center
    valign = center
}
