ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#859289'

typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#e67e80'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#d699b6'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[function]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[path]='fg=#7fbbb3'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#7fbbb3'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#d699b6'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#dbbc7f'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#dbbc7f'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#dbbc7f'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#dbbc7f'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#7fbbb3'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#859289'
