#!/usr/bin/env bash

set -euo pipefail

session="popup"

if ! tmux has -t "$session" 2> /dev/null; then
  tmux new-session -d -s "$session"
  tmux set-option -s -t "$session" key-table popup
  tmux set-option -s -t "$session" status off
  tmux set-option -s -t "$session" prefix None
fi

exec tmux attach -t "$session" > /dev/null
