require("config.autocmds")
require("config.keymaps")
require("config.options")
require("config.mini")

require("plugins.colorscheme")
require("plugins.completion")
require("plugins.conform")
require("plugins.lsp")
require("plugins.mini")
require("plugins.misc")
require("plugins.noice")
require("plugins.snacks")
require("plugins.treesitter")
