all:
	(wget -q https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.47/icon_map.lua -O icon_map.lua) >/dev/null
	(cd event_providers && $(MAKE)) >/dev/null
	(cd menus && $(MAKE)) >/dev/null
