[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.commands'

        [catalogs.globalScopes.scope]
        kind = 'none'

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 35
    carbonModifiers = 256

[settings]
clipboardHistoryRetention = 'sevenDays'
themeIdentifier = 'com.brnbw.tuna.themes.NormieBar'
