#!/bin/sh

bspc monitor DisplayPort-2 -d   I II III IV
bspc monitor HDMI-A-1 -d        V VI VII VIII

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp       desktop='^8' state=floating follow=on
bspc rule -a Chromium   desktop='^2'
bspc rule -a mplayer2   state=floating
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off

wmname LG3D

#sxhkd &
#polybar primary &
#polybar secondary &

pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x polybar > /dev/null && polybar -r primary && polybar -r secondary \
#    || polybar primary & polybar secondary &

sh $HOME/.config/polybar/launch.sh
