#!/usr/bin/env bash

LAYOUT_NAME="40% : 30% : 30% (70% : 30%)"

if [[ "$1" == "--name" ]]; then
    printf "%s\n" "$LAYOUT_NAME"
    exit 0
fi

tmux split-window -h -p 30 -c "#{pane_current_path}"
tmux select-pane -L
tmux split-window -h -p 43 -c "#{pane_current_path}"
tmux select-pane -R
tmux split-window -v -p 30 -c "#{pane_current_path}"
