#!/usr/bin/env bash

LAYOUT_NAME="50% : 25% : 25% (70% : 30%)"

if [[ "$1" == "--name" ]]; then
    printf "%s\n" "$LAYOUT_NAME"
    exit 0
fi

tmux split-window -h -p 50 -c "#{pane_current_path}"
tmux split-window -h -p 50 -c "#{pane_current_path}"
tmux split-window -v -p 30 -c "#{pane_current_path}"
