cask_args appdir: '/Applications'

# Taps
tap "nikitabobko/tap" # Aerospace
tap "jsattler/tap" # BetterCapture
tap "bfpimentel/dotfiles" # Neovim

# Mac Store
mas "Quickdrop", id: 6740147178

# Brews
brew "dockutil"

brew "zinit"
brew "tmux"
brew "tpm"
brew "stow"

brew "lua"

brew "cocoapods"

brew "pnpm"
brew "uv"
brew "overmind"
brew "direnv"

brew "lazygit"
brew "gnupg"
brew "ripgrep"
brew "libpcap"
brew "eza"
brew "xz"
brew "xh"
brew "fzf"
brew "wget"

brew "opencode"

brew "qt"
brew "create-dmg"

brew "podman"
brew "podman-compose"
brew "redis"
brew "postgresql@17"

brew "tree-sitter"

brew "ruff"

brew "lua-language-server"
brew "stylua"

brew "bash-language-server"
brew "beautysh"

brew "yaml-language-server"
brew "yamlfmt"

brew "typescript-language-server"
brew "tailwindcss-language-server"
brew "vscode-langservers-extracted"

# Casks
cask "kitty@nightly"
cask "neovim-nightly"

cask "flutter"
cask "xcodes-app"
cask "android-commandlinetools"

cask "vial"
cask "betterdisplay"
cask "linearmouse"
cask "hiddenbar"
cask "the-unarchiver"
cask "raycast"
cask "eqmac"

cask "aerospace"

cask "bettercapture"
cask "helium-browser"
cask "shottr"
cask "pearcleaner"
cask "ankerwork"
cask "tailscale-app"
cask "mullvad-vpn@beta"

cask "bruno"
cask "http-toolkit"
cask "macfuse"
cask "gcloud-cli"

cask "moonlight"
cask "anydesk"

cask "font-victor-mono-nerd-font"
cask "font-commit-mono-nerd-font"
cask "sf-symbols"
